Controllers/CarisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using StokTakip_v3._0.Models;

namespace StokTakip_v3._0.Controllers
{
    public class CarisController : Controller
    {
        private StokEntities1 db = new StokEntities1();

        // GET: Caris
        public ActionResult Index()
        {
            var cari = db.Cari.Include(c => c.ilce);
            return View(cari.ToList());
        }

        // GET: Caris/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cari cari = db.Cari.Find(id);
            if (cari == null)
            {
                return HttpNotFound();
            }
            return View(cari);
        }

        // GET: Caris/Create
        public ActionResult Create()
        {
            ViewBag.iller = db.il;
            //ViewBag.ılce_id = new SelectList(db.ilce, "id", "ad");
            return View();
        }

        // POST: Caris/Create
        // Aşırı gönderim saldırılarından korunmak için, lütfen bağlamak istediğiniz belirli özellikleri etkinleştirin, 
        // daha fazla bilgi için https://go.microsoft.com/fwlink/?LinkId=317598 sayfasına bakın.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Cari cari)
        {
            if (ModelState.IsValid)
            {
                
                db.Cari.Add(cari);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ılce_id = new SelectList(db.ilce, "id", "ad", cari.ılce_id);
            ViewBag.iller = db.il;
            return View(cari);
        }

        // GET: Caris/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cari cari = db.Cari.Find(id);
            if (cari == null)
            {
                return HttpNotFound();
            }
            ViewBag.iller = db.il;
            return View(cari);
        }

        // POST: Caris/Edit/5
        // Aşırı gönderim saldırılarından korunmak için, lütfen bağlamak istediğiniz belirli özellikleri etkinleştirin, 
        // daha fazla bilgi için https://go.microsoft.com/fwlink/?LinkId=317598 sayfasına bakın.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,Cari_ad,Cari_soyad,FirmaUnvani,Adres,Telefon,ılce_id")] Cari cari)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cari).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ılce_id = new SelectList(db.ilce, "id", "ad", cari.ılce_id);
            return View(cari);
        }

        // GET: Caris/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cari cari = db.Cari.Find(id);
            if (cari == null)
            {
                return HttpNotFound();
            }
            return View(cari);
        }

        // POST: Caris/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cari cari = db.Cari.Find(id);
            db.Cari.Remove(cari);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        
        public JsonResult Ilceler(int? ilid)
        {
            var output=db.ilce.Where(w => w.il_id == ilid).Select(s=>new { s.id,s.ad, s.il_id }).ToArray();
            
            return Json(output, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -STOK-TAKİP RAPORLAMA SİSTEMİ</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.16.0/dist/bootstrap-table.min.css">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("STOK-TAKİP", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Cari", "Index", "Caris")</li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                            Stok
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                @Html.ActionLink("Stok", "Index", "Stoks")
                            </li>
                            <li>
                                @Html.ActionLink("Stok Hareket", "Index", "Stok_Hareket")
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                            Depo
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                @Html.ActionLink("Depo", "Index", "Depoes")
                            </li>
                            <li>
                                @Html.ActionLink("Depo Hareket", "Index", "Depo_Hareket")
                            </li>
                            <li>
                                @Html.ActionLink("Depo Takip", "Index", "Depo_Takip")
                            </li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Kategoriler", "Index", "Kategoris")</li>
                    <li>@Html.ActionLink("Marka", "Index", "Markas")</li>
                    <li>@Html.ActionLink("Model", "Index", "Model")</li>
                    <li>@Html.ActionLink("Özellikler", "Index", "Ozelliklers")</li>
                    <li>@Html.ActionLink("Kategori Özellikleri", "Index", "Ozellik_iliski")</li>
                    <li>@Html.ActionLink("Raporlar", "Index", "Raporlars")</li>

                </ul>
                <ul class="nav  nav-bar pull-right" , style="color:white">
                    <li>@Html.ActionLink("ÇIKIŞ YAP", "Cikis", "Security")</li>

                </ul>

                <ul class="nav  nav-bar pull-right" , style="color:white">

                    <li>@Html.ActionLink("KAYIT OL", "Kayit", "Security")</li>
                </ul>
            </div>

        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap") 
    <script src="~/Scripts/moment.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.16.0/dist/bootstrap-table.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ASP.NET Uygulamam</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            
            
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>